interface FormData {
    id: string;
    name: string;
    description: string;
    price: string;
}

interface Translation {
    opsTitle: string;
    labelId: string;
    labelName: string;
    labelDescription: string;
    labelPrice: string;
    placeholderId: string;
    placeholderName: string;
    placeholderDescription: string;
    placeholderPrice: string;
    labelLoading: string;
    labelIdAutoGenerated: string;
    labelIdRequired: string;
    btnCreate: string;
    btnRead: string;
    btnUpdate: string;
    btnDelete: string;
    msgSuccess: string;
    msgPrompt: string;
}

// Global interface definitions for window properties
interface CustomWindow extends Window {
    i18n: { [key: string]: Translation };
    OperationPanel: React.FC;
    CreateOp: React.FC<any>;
    UpdateOp: React.FC<any>;
    DeleteOp: React.FC<any>;
}

const OperationPanel: React.FC = () => {
    const [formData, setFormData] = (window as any).React.useState({ id: '', name: '', description: '', price: '' } as FormData);
    const [status, setStatus] = (window as any).React.useState(null as string | null);
    const [loading, setLoading] = (window as any).React.useState(false);
    const [error, setError] = (window as any).React.useState(null as string | null);
    const [currentOp, setCurrentOp] = (window as any).React.useState(null as 'create' | 'update' | 'delete' | 'read' | null);
    const [showReadList, setShowReadList] = (window as any).React.useState(false);
    const [refreshKey, setRefreshKey] = (window as any).React.useState(0);
    const [savedSearch, setSavedSearch] = (window as any).React.useState({ id: '', name: '', description: '', price: '' } as FormData);
    const [savedPage, setSavedPage] = (window as any).React.useState(0);
    const [readSearch, setReadSearch] = (window as any).React.useState({ id: '', name: '', description: '', price: '' } as FormData);
    const lang = document.documentElement.lang || 'en';
    const t = (window as any).i18n[lang] || (window as any).i18n.en;

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData((prev: FormData) => ({ ...prev, [name]: value }));
    };

    const handleCreateSuccess = (createdProduct: any) => {
        setFormData({ id: createdProduct.id, name: createdProduct.name, description: createdProduct.description, price: createdProduct.price });
        setStatus(t.msgSuccess.replace('{0}', 'CREATE'));
        setError(null);
        if (showReadList) {
            setRefreshKey((k: number) => k + 1);
            setCurrentOp('read');
        } else {
            setCurrentOp(null);
        }
    };

    const handleCreateError = (errorMsg: string) => {
        setError(errorMsg);
        setStatus(null);
        setCurrentOp(null);
    };

    const handleUpdateSuccess = () => {
        setStatus(t.msgSuccess.replace('{0}', 'UPDATE'));
        setError(null);
        if (showReadList) {
            setRefreshKey((k: number) => k + 1);
            setCurrentOp('read');
        } else {
            setCurrentOp(null);
        }
    };

    const handleUpdateError = (errorMsg: string) => {
        setError(errorMsg);
        setStatus(null);
        setCurrentOp(null);
    };

    const handleDeleteSuccess = () => {
        setStatus(t.msgSuccess.replace('{0}', 'DELETE'));
        setError(null);
        if (showReadList) {
            setRefreshKey((k: number) => k + 1);
            setCurrentOp('read');
        } else {
            setCurrentOp(null);
        }
    };

    const handleDeleteError = (errorMsg: string) => {
        setError(errorMsg);
        setStatus(null);
        setCurrentOp(null);
    };

    const handleReadSuccess = (selectedProduct: FormData, searchCriteria: FormData, page: number) => {
        setSavedSearch(searchCriteria);
        setSavedPage(page);
        setReadSearch(searchCriteria);
        setShowReadList(true);
        setCurrentOp(null);
    };

    const handleReadListBack = (searchCriteria: FormData, page: number) => {
        setSavedSearch(searchCriteria);
        setSavedPage(page);
        setReadSearch(searchCriteria);
        setCurrentOp(null);
    };

    const handleReadError = (errorMsg: string) => {
        setError(errorMsg);
        setCurrentOp(null);
    };

    function handleSubmit(action: string) {
        if (action === 'create') {
            setCurrentOp('create');
            return;
        }
        if (action === 'update') {
            setCurrentOp('update');
            return;
        }
        if (action === 'delete') {
            setCurrentOp('delete');
            return;
        }
        if (action === 'read') {
            setReadSearch(formData);
            setSavedPage(0);
            setCurrentOp('read');
            return;
        }

        if (!formData.id.trim()) {
            setError("ID is required for this operation.");
            return;
        }

        setLoading(true);
        setStatus(null);
        setError(null);

        // Simulate for other actions
        setTimeout(() => {
            const isSuccess = action !== 'delete' || Math.random() > 0.5;
            setLoading(false);
            if (isSuccess) {
                setStatus(t.msgSuccess.replace('{0}', action.toUpperCase()));
                setError(null);
            } else {
                setError(`Error occurred during ${action} operation.`);
                setStatus(null);
            }
        }, 2000);
    };

    const CreateOp = (window as any).CreateOp;
    const UpdateOp = (window as any).UpdateOp;
    const DeleteOp = (window as any).DeleteOp;
    const ReadOp = (window as any).ReadOp;

    if (currentOp === 'create') {
        return (
            <CreateOp
                location={window.location.href}
                productDTO={formData}
                onSuccess={handleCreateSuccess}
                onError={handleCreateError}
                lang={lang}
            />
        );
    }

    if (currentOp === 'update') {
        return (
            <UpdateOp
                location={window.location.href}
                productDTO={formData}
                onSuccess={handleUpdateSuccess}
                onError={handleUpdateError}
                lang={lang}
            />
        );
    }

    if (currentOp === 'delete') {
        return (
            <DeleteOp
                location={window.location.href}
                id={formData.id}
                onSuccess={handleDeleteSuccess}
                onError={handleDeleteError}
                lang={lang}
            />
        );
    }

    if (currentOp === 'read') {
        return (
            <ReadOp
                location={window.location.href}
                productDTO={readSearch}
                setProductDTO={setFormData}
                onSuccess={handleReadSuccess}
                onError={handleReadError}
                onBack={handleReadListBack}
                lang={lang}
                refreshKey={refreshKey}
                initialPage={savedPage}
            />
        );
    }

    return (
        <div className="card shadow-lg border-0 mb-5">
            <div className="card-header bg-dark text-white px-4 py-3">
                <h4 className="mb-0 text-center">{t.opsTitle}</h4>
            </div>
            <div className="card-body p-4">
                <div className="alert alert-info mb-4">{t.labelHelpRead}</div>
                <form className="mb-4" onSubmit={(e) => e.preventDefault()}>
                    <div className="row g-3">
                        <div className="col-md-6">
                            <label className="form-label fw-bold">{t.labelId}</label>
                            <input
                                type="text"
                                name="id"
                                className="form-control"
                                placeholder={t.placeholderId}
                                value={formData.id}
                                onChange={handleInputChange}
                            />
                        </div>
                        <div className="col-md-6">
                            <label className="form-label fw-bold">{t.labelName}</label>
                            <input
                                type="text"
                                name="name"
                                className="form-control"
                                placeholder={t.placeholderName}
                                value={formData.name}
                                onChange={handleInputChange}
                            />
                        </div>
                        <div className="col-md-6">
                            <label className="form-label fw-bold">{t.labelDescription}</label>
                            <input
                                type="text"
                                name="description"
                                className="form-control"
                                placeholder={t.placeholderDescription}
                                value={formData.description}
                                onChange={handleInputChange}
                            />
                        </div>
                        <div className="col-md-6">
                            <label className="form-label fw-bold">{t.labelPrice}</label>
                            <input
                                type="text"
                                name="price"
                                className="form-control"
                                placeholder={t.placeholderPrice}
                                value={formData.price}
                                onChange={handleInputChange}
                            />
                        </div>
                    </div>

                    <div className="d-flex gap-3 mt-4 justify-content-center flex-wrap">
                        <button type="button" className="btn btn-lg btn-primary px-4" onClick={() => handleSubmit('create')} disabled={loading}>
                            <i className="bi bi-plus-circle me-2"></i>{t.btnCreate}
                        </button>
                        <button type="button" className="btn btn-lg btn-success px-4" onClick={() => handleSubmit('read')} disabled={loading}>
                            <i className="bi bi-search me-2"></i>{t.btnRead}
                        </button>
                        <button type="button" className="btn btn-lg btn-warning px-4" onClick={() => handleSubmit('update')} disabled={loading}>
                            <i className="bi bi-pencil-square me-2"></i>{t.btnUpdate}
                        </button>
                        <button type="button" className="btn btn-lg btn-danger px-4" onClick={() => handleSubmit('delete')} disabled={loading}>
                            <i className="bi bi-trash me-2"></i>{t.btnDelete}
                        </button>
                    </div>
                </form>

                {loading && (
                    <div className="alert alert-info mt-3 text-center border-0 shadow-sm animate__animated animate__fadeIn">
                        <strong><i className="bi bi-hourglass-split me-2"></i>{t.labelLoading}</strong>
                    </div>
                )}

                {error && (
                    <div className="alert alert-danger mt-3 text-center border-0 shadow-sm animate__animated animate__fadeIn">
                        <strong><i className="bi bi-exclamation-triangle me-2"></i>{error}</strong>
                    </div>
                )}

                {status && (
                    <div className="alert alert-success mt-3 text-center border-0 shadow-sm animate__animated animate__fadeIn">
                        <strong><i className="bi bi-check2-circle me-2"></i>{status}</strong>
                    </div>
                )}

                {!status && !loading && !error && (
                    <div className="text-center text-muted small italic">
                        {t.msgPrompt}
                    </div>
                )}
            </div>
        </div>
    );
};

(window as any).OperationPanel = OperationPanel;
